---
server:
  interface: local_interface:20500
  addresses: [global_address:20500, local_interface:20500]

service_locator:
  address: local_interface:20000
  username: registry_service
  password: admin_password
...
